export const CONSTANTS = {
  LIST: "list",
  EDIT: "edit",
  VIEW: "view",
  PLAY: "play",
  WORDSEARCH: "wordsearch",
  CROSSWORD: "crossword",
  SUDOKU: "sudoku",
  LOGIN: "login",
  SUCCESS: "success",
  ERROR: "error",
  TITLE: "title",
  DIFFICULTY: "difficulty",
  WORDS: "words",
  WIDTH: "width",
  HEIGHT: "height",
  PUZZLE: "puzzle",
};

export const STYLES = {
  NAV_LINK: "nav-link",
  NAV_ITEM: "nav-item",
  // NAV_OPTION: "nav-option",
  CURSOR_POINTER: "cursor-pointer",
  ACTIVE: "active",
  DISABLED: "disabled",
  LINK_PRIMARY: "link-primary",
  TAB_PANE: "tab-pane fade",
  TAB_PANE_ACTIVE: "tab-pane fade show active",
  FORM_INPUT: "form-control form-control-sm mb-1",
  FORM_GROUP: "form-group mb-2",
  MS_1: "ms-1",
  MB_2: "mb-2",
  MB_3: "mb-3",
  MT_2: "mt-2",
  MY_1: "my-1",
  PE_4: "pe-4",
  PY_2: "py-2",
  W_50: "w-50",
  W_75: "w-75",
  W_100: "w-100",
  D_FLEX: "d-flex",
  LIST_ITEMS: "d-flex flex-column align-items-start w-100",
  TEXT_SECONDARY: "text-secondary",
  BUTTON_CONTAINER: "d-flex flex-column align-items-start border-top pt-2 mt-3",
  FW_BOLD: "fw-bold",
  TEXT_END: "text-end",
  TABLE: "table table-striped table-hover border",
  TABLE_CONTAINER: "table-responsive",
  BUTTON_PRIMARY: "btn btn-primary",
  BUTTON_SECONDARY: "btn btn-secondary",
  BUTTON_WARNING: "btn btn-warning",
  TABLE_HEADER: "fw-bold clickable",
};